# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/e18777a5-3a52-4a3e-8857-a989242993af";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-a228b62a-ea4c-4ded-889d-69415d8e84e8".device = "/dev/disk/by-uuid/a228b62a-ea4c-4ded-889d-69415d8e84e8";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/24A2-CBFD";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  # Ensure BTRFS support is enabled (usually is by default)
  boot.supportedFilesystems = [ "btrfs" ];

  # Auto-mount the RAID at /mnt/rust
  fileSystems."/mnt/rust" = {
    label = "rust";
    fsType = "btrfs";
  };

  # If you want to create the mountpoint dir automatically (NixOS handles it, but explicit is fine)
  fileSystems."/mnt/rust".neededForBoot = false;  # Non-root, so optional

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp34s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
